### ISSUE TITLE
Precomputed variant should work with a threshold number of shares and not need all of them

### ISSUE THREAD

**Issue by cygnusv** [nucypher/ferveo#184] opened 2024-02-21 05:58 UTC

**Comment by piotr-roslaniec** [comment] 2024-02-29 09:59
This issue is caused by precomputed decryption shares using all domain points of all participants for Lagrange coefficients (pre)computing.

According to the [docs](https://github.com/nucypher/ferveo/blob/3eea8fdb55c3cc04491851de87e409e21538a91e/book/src/variants.md#precomputed):

> (...) you will first choose a specific sub-set of m nodes from n i.e pick an arbitrary m-of-n set of nodes (where m is the threshold), and those specific m nodes need to reply with precomputed decryption shares (...)

So in order to fix this, I will expose an interface where the caller (tDec decryption client) can specify said subset of participants to have decryption shares created for them.

**Comment by piotr-roslaniec** [comment] 2024-03-19 13:21
Closed by #185

**Closed by piotr-roslaniec** 2024-03-19 13:21 UTC
Labels: bug :bug:
